<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            ['name'=>'Egg Roll',
                'price'=>'2.59',
                'category'=>'appetizer',
                'description'=>'4 egg rolls',
                'gallery'=>'EggRoll.jpg'],
            ['name'=>'Crab Rangoon',
                'price'=>'2.99',
                'category'=>'appetizer',
                'description'=>'6 crab rangoons',
                'gallery'=>'CrabRangoon.jpg'],
            ['name'=>'Fried Dumpling',
                'price'=>'4.99',
                'category'=>'appetizer',
                'description'=>'6 fried dumplings',
                'gallery'=>'FriedDumpling.jpg'],
            ['name'=>'Bottle Water',
                'price'=>'0.99',
                'category'=>'drink',
                'description'=>'Bottle water',
                'gallery'=>'BottleWater.jpg'], 
            ['name'=>'Canned Soft Drink',
                'price'=>'1.25',
                'category'=>'drink',
                'description'=>'Soft drink canned',
                'gallery'=>'SoftDrinkCan.jpg'],
            ['name'=>'Funtain Soft Drink',
                'price'=>'0',
                'category'=>'drink',
                'description'=>'Funtain soft drink',
                'gallery'=>'SoftDrinkFuntain.jpg'],
            ['name'=>'Fresh Fruit Juice',
                'price'=>'0',
                'category'=>'drink',
                'description'=>'Fresh Fruit Juice',
                'gallery'=>'FreshJuice.jpg'],     
            ['name'=>'Fried Rice',
                'price'=>'0',
                'category'=>'side',
                'description'=>'Fried rice side',
                'gallery'=>'FriedRice.jpg'],
            ['name'=>'Chow Mein',
                'price'=>'0',
                'category'=>'side',
                'description'=>'Chow Mein side',
                'gallery'=>'ChowMein.jpg'],
            ['name'=>'BBQ Chicken',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'BBQ chicken entree',
                'gallery'=>'BBQChicken.jpg'],
            ['name'=>'Black Pepper Chicken',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'Black pepper chicken entree',
                'gallery'=>'BlackPepperChicken.jpg'],
            ['name'=>'General Taos Chicken',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'General Taos Chicken entree',
                'gallery'=>'GeneralTaosChicken.jpg'],
            ['name'=>'Jalapeno Chicken',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'Jalapeno Chicken entree',
                'gallery'=>'JalapenoChicken.jpg'],
            ['name'=>'Kung Pao Chicken',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'Kung pao chicken entree',
                'gallery'=>'KungPaoChicken.jpg'],
            ['name'=>'Mushroom Chicken',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'Mushroom chicken entree',
                'gallery'=>'MushroomChicken.jpg'],
            ['name'=>'Orange Chicken',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'Orange chicken entree',
                'gallery'=>'OrangeChicken.jpg'],
            ['name'=>'String Bean Chicken',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'String bean Chicken entree',
                'gallery'=>'.jpg'],
            ['name'=>'Teriyaki Chicken',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'Teriyaki chicken entree',
                'gallery'=>'TeriyakiChicken.jpg'],
            ['name'=>'Broccoli Beef',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'Broccoli Beef entree',
                'gallery'=>'BeefBroccoli.jpg'],
            ['name'=>'Hunan Beef',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'Hunan beef entree',
                'gallery'=>'HunanBeef.jpg'],
            ['name'=>'Pepper Steak',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'Pepper steak entree',
                'gallery'=>'.jpg'],   
            ['name'=>'Broccoli Shrimp',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'Dinner for shrimp entree',
                'gallery'=>'BroccoliShrimp.jpg'],
            ['name'=>'Kung Pao Shrimp',
                'price'=>'0',
                'category'=>'entree',
                'description'=>'Kung Pao Shrimp entree',
                'gallery'=>'.jpg']
            
        ]);
    }
}
